# Generated by Django 4.1.1 on 2022-10-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.TextField()),
                ('Last_name', models.TextField()),
                ('profile_picture', models.ImageField(upload_to='')),
                ('username', models.TextField()),
                ('email_id', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=8)),
                ('confirm_password', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=20)),
                ('line1', models.CharField(max_length=20)),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('pincode', models.IntegerField()),
            ],
        ),
    ]
